### ISSUE TITLE
Throttle comes back to 1

### ISSUE THREAD

**Issue by EloxZ** [untoldwind/KontrolSystem2#45] opened 2023-03-21 19:00 UTC
```c
while (isActive) {
  if (vessel.situation == "Landed") {
      CONSOLE.clear()
      CONSOLE.print_line("Landed")
      vessel.set_throttle(0)
      isActive = false
  } else if ((vessel.vertical_surface_speed < -2)) {
      keepSealevelAltitude(vessel, landAltitude, true)
  } else {
      setThrottleTo(vessel, 0)
  }
}
```
I'm trying to set the throttle to 0 when the vessel lands, but it comes back to 1 when the script ends, messing the landing. I'm running the script with throttle already 0, therefore, it should revert back to 0, as I understand. The code ends the loop with set_throttle(0), so I thought the issue was that `keepSealevelAltitude()`  sets the throttle to 1 after this, because is async. But, I added `if (isLanding && vessel.situation == "Landed") vessel.set_throttle(0)` at the end.

**Comment by untoldwind** [comment] 2023-03-21 20:22
There is a bit of misunderstanding here (i.e. documentation is lacking):
`vessel.set_throttle` does not just set the throttle to a specific value, it actually creates a `ThrottleManager` that is taking over control until it is either explicitly released via `manager.release()` or the script terminates.

Calling `vessel.set_throttle` creates two ThrottleManagers that are competing with each other ;)
Which is probably something of a bug. I will add some logic that a subsequent call to `.set_throttle` will release any previous ThrottleManager that a attached to the vessel.

The reason for this somewhat complicated setup is, that I add a Hook to `VesselBehavior.OnPreAutopilotUpdate` and I need some sort of handle in the script to know when the hook can be released again.
Maybe there is a better way of doing this.

**Comment by EloxZ** [comment] 2023-03-21 21:46
I've solved it with `let manager = vessel.set_throttle(0)` , using `manager.throttle = value` and calling `manager.release()` at the end.

**Comment by untoldwind** [comment] 2023-03-23 08:33
In the 0.2.1 version subsequent calls to `.set_throttle` will return the same instance. So
```
const manager = vessel.set_throttle(0.5)
manager.throttle = 1
```
should be the same as
```
const manager = vessel.set_throttle(0.5)
vessel.set_throttle(1)
```
... of course the manager should still be release at the end

**Comment by untoldwind** [comment] 2023-04-23 11:33
ThrottleManager seems to work (mostly) as intended, so closing this for now

**Closed by untoldwind** 2023-04-23 11:33 UTC
Labels: documentation, enhancement, probably fixed
